volumes:
  postgres-data:
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOSTNAME=localhost
    volumes:
      - postgres-data:/var/lib/postgresql/data

  service:
    build:
      context: ./
      dockerfile: ./deployments/Dockerfile
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./tables:/root/tables
    environment:
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      - DB_MIN_CONNS=${DB_MIN_CONNS}
      - DB_MAX_CONNS=${DB_MAX_CONNS}
      - CSV_FILE=${CSV_FILE}
      - WORKER_POOL_GOROUTINES=${WORKER_POOL_GOROUTINES}
      - BATCH_SIZE=${BATCH_SIZE}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - MIGRATIONS_DIR=/root/migrations
    depends_on:
      - db